upstreamProjects:
  Mule-runtime/mule-integration-tests/master-FEBRUARY-2023,
  Mule-runtime/mule-http-service/master-FEBRUARY-2023,
  Mule-runtime/mule-oauth-service/master-FEBRUARY-2023,
  Mule-runtime/mule-scheduler-service/master-FEBRUARY-2023,
  Mule-runtime/mule-soap-service/master,
  Mule-runtime/mule-embedded-api/master-FEBRUARY-2023,
  Mule-runtime/mule-maven-client/master-FEBRUARY-2023
archiveArtifacts: "**/logs/**,**/conf/wrapper*.conf"
# MULE-18045: Comment public setting to get raml-parser 2 from private repo until it is released in a public repo
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
projectType: runtime
