upstreamProjects:
  Mule-runtime/mule-integration-tests/4.5.0-rc10,
  Mule-runtime/mule-http-service/1.7.0-rc10,
  Mule-runtime/mule-oauth-service/2.2.0-rc10,
  Mule-runtime/mule-scheduler-service/1.5.0-rc10,
  Mule-runtime/mule-soap-service/master,
  Mule-runtime/mule-embedded-api/1.5.0-rc10,
  Mule-runtime/mule-maven-client/2.0.0-rc10
archiveArtifacts: "**/logs/**,**/conf/wrapper*.conf"
# MULE-18045: Comment public setting to get raml-parser 2 from private repo until it is released in a public repo
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
projectType: runtime
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk8:
    testJdkTool: OPEN-JDK8
  jdk11:
    testJdkTool: OPEN-JDK11
