upstreamProjects:
  Mule-runtime/mule-integration-tests/master-MARCH-2024,
  Mule-runtime/mule-http-service/master-MARCH-2024,
  Mule-runtime/mule-oauth-service/master-MARCH-2024,
  Mule-runtime/mule-scheduler-service/master-MARCH-2024,
  Mule-runtime/mule-soap-service/master-MARCH-2024,
  Mule-runtime/mule-embedded-api/master-MARCH-2024,
  Mule-runtime/mule-maven-client/master-MARCH-2024
archiveArtifacts: "**/logs/**,**/conf/wrapper*.conf"
# MULE-18045: Comment public setting to get raml-parser 2 from private repo until it is released in a public repo
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
projectType: runtime
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk8:
    testJdkTool: OPEN-JDK8
  jdk11:
    testJdkTool: OPEN-JDK11
