upstreamProjects:
  Mule-runtime/mule-integration-tests/support/4.6.x,
  Mule-runtime/mule-http-service/support/1.8.x,
  Mule-runtime/mule-oauth-service/support/2.3.x,
  Mule-runtime/mule-scheduler-service/support/1.6.x,
  Mule-runtime/mule-soap-service/support/1.6.x,
  Mule-runtime/mule-embedded-api/rel/1.6.4,
  Mule-runtime/mule-maven-client/rel/2.1.4
archiveArtifacts: "**/logs/**,**/conf/wrapper*.conf"
# MULE-18045: Comment public setting to get raml-parser 2 from private repo until it is released in a public repo
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
projectType: runtime
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk8:
    testJdkTool: OPEN-JDK8
  jdk11:
    testJdkTool: OPEN-JDK11
