upstreamProjects:
  Mule-runtime/mule-integration-tests/4.4.0-JANUARY-2024,
  Mule-runtime/mule-http-service/1.6.17,
  Mule-runtime/mule-oauth-service/2.1.3,
  Mule-runtime/mule-scheduler-service/1.4.3,
  Mule-runtime/mule-soap-service/1.4.10,
  Mule-runtime/mule-embedded-api/1.4.0-JANUARY-2024,
  Mule-runtime/mule-maven-client/1.6.0-JANUARY-2024
archiveArtifacts: "**/logs/**,**/conf/wrapper*.conf"
# MULE-18045: Comment public setting to get raml-parser 2 from private repo until it is released in a public repo
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
projectType: runtime
