upstreamProjects:
  Mule-runtime/mule-integration-tests/master-JUNE-2025,
  Mule-runtime/mule-http-service/master-JUNE-2025,
  Mule-runtime/mule-oauth-service/master-JUNE-2025,
  Mule-runtime/mule-scheduler-service/master-JUNE-2025,
  Mule-runtime/mule-soap-service/1.8.1,
  Mule-runtime/mule-embedded-api/master-JUNE-2025,
  Mule-runtime/mule-maven-client/master-JUNE-2025
archiveArtifacts: "**/logs/**,**/conf/wrapper*.conf"
# MULE-18045: Comment public setting to get raml-parser 2 from private repo until it is released in a public repo
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
projectType: runtime
mavenTool: "3.9.9"
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk21:
    testJdkTool: TEMURIN-JDK21
