upstreamProjects:
  Mule-runtime/mule-integration-tests/4.8.2-DRY-RUN,
  Mule-runtime/mule-http-service/1.10.2-DRY-RUN,
  Mule-runtime/mule-oauth-service/2.5.2-DRY-RUN,
  Mule-runtime/mule-scheduler-service/1.8.2-DRY-RUN,
  Mule-runtime/mule-soap-service/support/1.8.x,
  Mule-runtime/mule-embedded-api/1.8.2-DRY-RUN,
  Mule-runtime/mule-maven-client/2.3.2-DRY-RUN
archiveArtifacts: "**/logs/**,**/conf/wrapper*.conf"
# MULE-18045: Comment public setting to get raml-parser 2 from private repo until it is released in a public repo
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
projectType: runtime
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk8:
    testJdkTool: OPEN-JDK8
  jdk11:
    testJdkTool: OPEN-JDK11
