upstreamProjects:
  Mule-runtime/mule-integration-tests/master-OCTOBER-2024,
  Mule-runtime/mule-http-service/master-OCTOBER-2024,
  Mule-runtime/mule-oauth-service/master-OCTOBER-2024,
  Mule-runtime/mule-scheduler-service/master-OCTOBER-2024,
  Mule-runtime/mule-soap-service/master-OCTOBER-2024,
  Mule-runtime/mule-embedded-api/master-OCTOBER-2024,
  Mule-runtime/mule-maven-client/master-OCTOBER-2024
archiveArtifacts: "**/logs/**,**/conf/wrapper*.conf"
# MULE-18045: Comment public setting to get raml-parser 2 from private repo until it is released in a public repo
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
projectType: runtime
mavenTool: "3.9.9"
jdkTool: OPEN-JDK17
