upstreamProjects:
  Mule-runtime/mule-integration-tests/4.9.5,
  Mule-runtime/mule-http-service/1.11.4,
  Mule-runtime/mule-oauth-service/2.6.4,
  Mule-runtime/mule-scheduler-service/1.9.4,
  Mule-runtime/mule-soap-service/1.9.1,
  Mule-runtime/mule-embedded-api/1.9.5,
  Mule-runtime/mule-maven-client/2.4.5
archiveArtifacts: "**/logs/**,**/conf/wrapper*.conf"
# MULE-18045: Comment public setting to get raml-parser 2 from private repo until it is released in a public repo
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
projectType: runtime
mavenTool: "3.9.9"
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk21:
    testJdkTool: TEMURIN-JDK21
