upstreamProjects:
  Mule-runtime/mule-integration-tests/4.4.0-MAY-2022,
  Mule-runtime/mule-http-service/1.6.6,
  Mule-runtime/mule-oauth-service/2.1.2,
  Mule-runtime/mule-scheduler-service/1.4.2,
  Mule-runtime/mule-soap-service/support/1.4.x,
  Mule-runtime/mule-embedded-api/1.4.0-MAY-2022,
  Mule-runtime/mule-maven-client/1.6.0-MAY-2022
archiveArtifacts: "**/logs/**,**/conf/wrapper*.conf"
# MULE-18045: Comment public setting to get raml-parser 2 from private repo until it is released in a public repo
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
projectType: runtime
