upstreamProjects:
  Mule-runtime/mule-integration-tests/master-OCTOBER-2023,
  Mule-runtime/mule-http-service/master,
  Mule-runtime/mule-oauth-service/master,
  Mule-runtime/mule-scheduler-service/master,
  Mule-runtime/mule-soap-service/master,
  Mule-runtime/mule-embedded-api/master-OCTOBER-2023,
  Mule-runtime/mule-maven-client/master-OCTOBER-2023
archiveArtifacts: "**/logs/**,**/conf/wrapper*.conf"
# MULE-18045: Comment public setting to get raml-parser 2 from private repo until it is released in a public repo
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
projectType: runtime
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk8:
    testJdkTool: OPEN-JDK8
  jdk11:
    testJdkTool: OPEN-JDK11
