upstreamProjects:
  Mule-runtime/mule-integration-tests/4.6.16-DRY-RUN,
  Mule-runtime/mule-http-service/1.8.16-DRY-RUN,
  Mule-runtime/mule-oauth-service/2.3.16-DRY-RUN,
  Mule-runtime/mule-scheduler-service/1.6.16-DRY-RUN,
  Mule-runtime/mule-soap-service/1.6.16-DRY-RUN,
  Mule-runtime/mule-embedded-api/1.6.16-DRY-RUN,
  Mule-runtime/mule-maven-client/2.1.16-DRY-RUN
archiveArtifacts: "**/logs/**,**/conf/wrapper*.conf"
# MULE-18045: Comment public setting to get raml-parser 2 from private repo until it is released in a public repo
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
projectType: runtime
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk8:
    testJdkTool: OPEN-JDK8
  jdk11:
    testJdkTool: OPEN-JDK11
